#!/bin/bash
set -e

#DEBHELPER#

case "$1" in
    configure)

        if [ -z "$2" ]; then
            for i in apache apache-perl apache-ssl; do
                if [ -r /etc/$i/modules.conf ]; then
                        /usr/sbin/apache-modconf $i enable mod_ldap_cfg
                fi
            done
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "$0: didn't understand being called with \`$1'" 1>&2
        exit 1
    ;;
esac

exit 0

