#!/bin/bash
set -e

#DEBHELPER#

case "$1" in
    upgrade|failed-upgrade)
    ;;

    deconfigure|remove)
        for i in apache apache-perl apache-ssl; do
            if [ -r /etc/$i/modules.conf ]; then
                /usr/sbin/apache-modconf $i disable mod_ldap_cfg quiet
            fi
        done
    ;;

    *)
        echo "$0: didn't understand being called with \`$1'" 1>&2
        exit 1
    ;;
esac

exit 0

